### ISSUE TITLE
I found the data corruption culprit!

### ISSUE THREAD

**Issue by ammarfaizi2** [TeaInside/teavpn2#14]
We have been testing TeaVPN2 and still can't achieve a stable connection state when the traffic is crowded. I suspected there is data corruption in the event loop. Today I found the problem, and it is indeed data corruption.

This data corruption will not be detected by Valgrind, because the read/write to memory is all done legally to the correct memory address. However, the read/write mechanism is not legal for the event loop.

Below is the explanation (image attached):

![teavpn_invalid_pakcet](https://user-images.githubusercontent.com/26004054/95675265-1fdba400-0be0-11eb-8556-2edf1d7f3be4.png)

**Comment by ammarfaizi2** [comment]
Cc: @louvian @zeheater

**Comment by zeheater** [comment]
Great findings. How do we solve this problem ?
Aggregate the buffer and only process completed frame ?

**Comment by ammarfaizi2** [comment]
I am considering two solutions for this bug:
1. **Adjust** the recv size based on the received header packet **length**. So we can guarantee that only **a single packet is read at a time**. This solution has an overhead because the number of **recv syscalls** and **loop cycles** will **increase** just only to address a single packet.
2. Detect whether **partial bytes of the next packet** has arrived or not. If it has, use `memmove` to **shift** it to the **front of the buffer**. The call to `memmove` itself is the overhead, as we know `memmove` has overlap memory recovery routine.

Both of them have overhead, which is the smaller overhead?

The code hotspot:
https://github.com/TeaInside/teavpn2/blob/306c4b46d51e560dc142597c18bc519fdcff1387/src/sources/teavpn2/server/sock/tcp/server.c#L650-L726

**Comment by louvian** [comment]
Nice bug report @ammarfaizi2!
I vote for the memmove solution. I think local memory copy overhead is
cheaper than reading from a network I/O overhead. Beside that, the copied
area may not overlap, so the overlap overhead may exist or may not exist,
depending on the packet length that takes place.

Regards,
Louvian Lyndal

**Comment by ammarfaizi2** [comment]
I like that reason, I am going to go with `memmove` approach. I will address this issue through https://github.com/TeaInside/teavpn2/pull/13
