### ISSUE TITLE
Handle verbose level

### ISSUE THREAD

**Issue by ammarfaizi2** [TeaInside/teavpn2#24]
Add verbose level for log output support.

https://github.com/TeaInside/teavpn2/blob/e924c1b3cc6210419d88ef1300049689a6264ace/src/teavpn2/server/argv.c#L95-L96

**Comment by louvian** [comment]
Time to close this?
We have https://github.com/TeaInside/teavpn2/blob/1edb2cc4829a9da3b1e839283c5e4eb31ccc63ab/src/teavpn2/server/entry.c#L97-L102

**Comment by ammarfaizi2** [comment]
Oh yes, I am closing this. Thanks.
