### ISSUE TITLE
`ret` maybe uninitialized in `put_udp_session`

### ISSUE THREAD

**Issue by louvian** [TeaInside/teavpn2#27]
@ammarfaizi2, in commit 667576c933d0c2d74e5313f9565be338b418e905 ("udp_session.c: implement put_udp_session") you forgot to initialize the `int ret`. If `state->sess_map` is `NULL`, you will return an uninitialized value.

https://github.com/TeaInside/teavpn2/blob/667576c933d0c2d74e5313f9565be338b418e905/src/teavpn2/server/linux/udp_session.c#L188-L201

**Comment by ammarfaizi2** [comment]
@louvian Ah, good catch. Let me fix this real quick. I wonder why GCC did not warn me about this. I believe I've compiled it on my local machine, but didn't get warned.

**Comment by ammarfaizi2** [comment]
Fixed in bebbd12169defd2d96183deaee9bf072a3cb28ca, thanks for reporting. I am closing this.

**Comment by louvian** [comment]
Clang gives this
```
src/teavpn2/server/linux/udp_session.c:195:6: warning: variable 'ret' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
        if (state->sess_map)
            ^~~~~~~~~~~~~~~
src/teavpn2/server/linux/udp_session.c:200:9: note: uninitialized use occurs here
        return ret;
               ^~~
src/teavpn2/server/linux/udp_session.c:195:2: note: remove the 'if' if its condition is always true
        if (state->sess_map)
        ^~~~~~~~~~~~~~~~~~~~
src/teavpn2/server/linux/udp_session.c:192:9: note: initialize the variable 'ret' to silence this warning
        int ret;
               ^
                = 0
```

**Comment by ammarfaizi2** [comment]
I admit clang has better static analysis than GCC. But still, I mainly use GCC these days, or usually I compile with both, haha.

I usually invoke this when I want to test something out:
```
make -j4 CC=clang CXX=clang++
```
