### ISSUE TITLE
An improper locking bug(e.g., deadlock) on the lock client->mutex

### ISSUE THREAD

**Issue by ryancaicse** [TeaInside/teavpn2#30]
Hi, developers, thank you for your checking. It seems the lock **client->mutex** is not released correctly when **unlikely(!client->is_used)** in the function **destroy_state**?

https://github.com/TeaInside/teavpn2/blob/d1a999952ca44210a904d4061529615334a3b032/src/teavpn2/server/linux/tcp_mt.c#L691-L708

**Comment by ammarfaizi2** [comment]
Same reason with https://github.com/TeaInside/teavpn2/issues/31#issuecomment-914363984

Thanks for visiting this repo.
