### ISSUE TITLE
An improper locking bug(e.g., deadlock) on the lock state->mutex

### ISSUE THREAD

**Issue by ryancaicse** [TeaInside/teavpn2#31]
Hi, developers, thank you for your checking. It seems the lock **state->mutex** is not released correctly when **unlikely(err != 0)** in the function **init_thread**?

https://github.com/TeaInside/teavpn2/blob/d1a999952ca44210a904d4061529615334a3b032/src/teavpn2/server/linux/tcp_mt.c#L470-L481

**Comment by ammarfaizi2** [comment]
Hi @ryancaicse,
Absolutely, but we no longer use the lock anymore right after it fails. So it's acceptable.

But yeah, I agree it should be released in anyway and I should use some kind of `__releases` and `__aqcuires` to self document this locking part for each function.

But, I don't maintain that code anymore (it's never really working, we don't have multithreading support in the current master branch). If you're interested in reading the code, you may visit the `udp_support` branch (I have recoded everything from zero). Let's ignore this code.

I am currently actively maintaining this branch https://github.com/TeaInside/teavpn2/tree/udp_support
